import { Check } from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader";
import { MockBanner } from "@/components/common/MockBanner";
import { WorkflowStepper } from "@/components/layout/WorkflowStepper";
import { LayoutDiagram } from "@/modules/layout/LayoutDiagram";
import { deriveLayoutCandidates } from "@/modules/model/derive";
import { useProjectStore } from "@/store/projectStore";
import type { Project } from "@/types";
import { fmtNum } from "@/utils/format";
import { cn } from "@/lib/utils";
import { t } from "@/data/strings/en";

export function LayoutSelectionPage({ project }: { project: Project }) {
  const selectLayout = useProjectStore((s) => s.selectLayout);
  const candidates = deriveLayoutCandidates(project);
  const { panelCount, area } = project.array;

  return (
    <div className="space-y-6">
      <PageHeader
        code="Step 03"
        title={t.nav.layout}
        description={`Candidate configurations for ${panelCount} panels in a ${area.widthM} × ${area.lengthM} m area. Format: rows × columns × tables.`}
      />
      <MockBanner>Layouts are generated by a placeholder enumerator. The Array/Layout Engine will replace this with the real optimisation algorithm.</MockBanner>

      {candidates.length === 0 ? (
        <div className="rounded-sm border border-dashed p-10 text-center text-sm text-muted-foreground">
          No regular configuration found for {panelCount} panels. Adjust the panel count.
        </div>
      ) : (
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
          {candidates.map((l) => {
            const selected = l.id === project.selectedLayoutId;
            return (
              <button key={l.id} onClick={() => selectLayout(project.id, l.id)}
                className={cn("flex flex-col rounded-sm border bg-card text-left transition-colors hover:border-primary", selected && "border-primary ring-1 ring-primary")}>
                <div className="flex items-center justify-between border-b px-3 py-2">
                  <span className="num text-base font-semibold">{l.label}</span>
                  <div className="flex items-center gap-2">
                    <span className={cn("font-mono text-[10px] uppercase", l.fitsArea ? "text-success" : "text-destructive")}>
                      {l.fitsArea ? "Fits area" : "Exceeds area"}
                    </span>
                    {selected && <span className="flex size-5 items-center justify-center rounded-full bg-primary text-primary-foreground"><Check className="size-3" /></span>}
                  </div>
                </div>
                <div className="eng-grid flex h-40 items-center justify-center p-3">
                  <LayoutDiagram layout={l} className="max-h-full w-full" />
                </div>
                <div className="grid grid-cols-3 gap-2 border-t px-3 py-2 font-mono text-[11px] text-muted-foreground">
                  <div><div className="text-[9px] uppercase">Footprint</div><div className="text-foreground">{fmtNum(l.footprintLengthM, 1)} × {fmtNum(l.footprintWidthM, 1)} m</div></div>
                  <div><div className="text-[9px] uppercase">Tables</div><div className="text-foreground">{l.tables}</div></div>
                  <div><div className="text-[9px] uppercase">Utilisation</div><div className="text-foreground">{fmtNum(l.utilisation * 100, 0)} %</div></div>
                </div>
              </button>
            );
          })}
        </div>
      )}
      <WorkflowStepper projectId={project.id} step="layout" nextDisabled={!project.selectedLayoutId} />
    </div>
  );
}
